version: 2.0

jobs:
  build:
  
    docker:
      - image: ubuntu:latest
       
    resource_class: large
  
    steps:
      - checkout
      - run: apt update -y
      - run: df -h && nproc && free -h
      - run: DEBIAN_FRONTEND=noninteractive apt install python3 wget ffmpeg neofetch python3.12-venv -y
      - run: neofetch && ls
      - run: wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O yt-dlp
      - run: chmod +x yt-dlp && mv yt-dlp /usr/local/bin/ && yt-dlp --version 
      - run: yt-dlp -f "bestvideo+bestaudio/best" --merge-output-format mkv "https://youtube.com/playlist?list=PL_A4M5IAkMaexM2nxZt512ESPt83EshJq&feature=shared"
      
      
